name: Auto-Test CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-generation:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]
        
    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build
      run: npm run build
      
    - name: Run tests
      run: npm test
      
    - name: Validate examples
      run: npm run validate
      
    - name: Run CI mode on example projects
      run: |
        PROJECTS=(
          "examples/react-app"
          "examples/nextjs-app"
          "examples/express-app"
          "examples/koa-app"
          "examples/hapi-app"
          "examples/fastify-app"
          "examples/hono-app"
          "examples/nestjs-app"
          "examples/graphql-app"
          "examples/vuejs-app"
          "examples/svelte-app"
        )
        
        for project in "${PROJECTS[@]}"; do
          echo "Testing $project"
          cd "$project"
          ../../dist/cli.js --ci --provider gemini .
          cd ../..
        done
      env:
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
